app_config:
  app_port: 8080
  metric_port: 7070
  write_timeout: 15
  read_time_out: 15
  idle_timeout: 15
auth_config:
  token_expire_time: 1440
  jwt_secret: "usersvc#secret"
  o_auth_client_id: "id"
  o_auth_client_secret: "secret"
  o_auth_redirect_url: "http://localhost:8080/auth/google/callback"
